### ISSUE TITLE
Zero Division Error

### ISSUE THREAD

**Issue by panjames** [idrdex/star-django#14] opened 2015-08-27 20:18 UTC
http://dev.stargeo.io/analysis/84/log/

**Comment by Suor** [comment] 2015-08-28 05:28
A duplicate of #16. A rerun is here - http://dev.stargeo.io/analysis/122/log/

**Closed by Suor** 2015-08-28 05:28 UTC

**Comment by Suor** [comment] 2015-08-31 11:37
This appeared to be actual bug in analysis code. Created #19 to track that.
