### ISSUE TITLE
KeyError: 'p'

### ISSUE THREAD

**Issue by panjames** [idrdex/star-django#27] opened 2015-09-29 00:13 UTC
http://dev.stargeo.io/analysis/234/log/

**Comment by panjames** [comment] 2015-10-01 01:13
Another one: http://dev.stargeo.io/analysis/235/log/

**Comment by Suor** [comment] 2015-10-01 13:16
The issue is caused by a fact that each study in those analysis is single-class: only case or only control.  So analysis doesn't work. I added a nicer message http://dev.stargeo.io/analysis/235/log/. 

P.S. This is usually a consequence of no series ever annotated with both case and control tag http://dev.stargeo.io/search/?q=tag%3ABEnd_Samples+tag%3AHuman_Fibroblasts

**Comment by panjames** [comment] 2015-10-01 17:48
A large number (in fact, all my studies) of studies unfortunately do not have cases and controls within the same GSE. There will be a lot of mixing and matching. And it sounds like, in combination with the study number > 1 requirement, we need at least two studies, both of which have cases and controls. Unfortunately, this isn't the case for the majority of analyses that I'm running. Is there any way to mitigate this issue?

cc @idrdex -- any thoughts?

**Comment by idrdex** [comment] 2015-10-02 16:02
This will be fixed when min samples filter added to analysis: https://github.com/idrdex/star-django/issues/28

**Closed by idrdex** 2015-10-02 16:02 UTC
