### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by panjames** [idrdex/star-django#15] opened 2015-08-27 20:18 UTC
http://dev.stargeo.io/analysis/85/log/

**Comment by Suor** [comment] 2015-08-28 05:27
Duplicate of #16.

**Comment by Suor** [comment] 2015-08-28 05:27
A rerun is here - http://dev.stargeo.io/analysis/123/log/

**Closed by Suor** 2015-08-28 05:27 UTC

**Comment by Suor** [comment] 2015-08-31 11:39
This was caused by mistyped control_query. Added a nice FAIL message.
