### ISSUE TITLE
Deleting sample_tags and validations

### ISSUE THREAD

**Issue by idrdex** [idrdex/star-django#23] opened 2015-09-24 21:27 UTC
We need a way to delete sample tags and all associated validations.  See: http://dev.stargeo.io/annotations/1609/samples/ for DHF annotation. I'd like to delete this sample_tag altogether since none of the samples are DHF.  I tried to validate and set all the DHF values as empty.  However, since the DHF tag is univarate,  best_kappa is not defined, and the annotation calls will not consider two empty annotation vectors, or will it?

**Comment by Suor** [comment] 2015-10-01 10:46
Best annotation is determined by a bit complicated set of rules. First validation satisfying any of the following is selected:
- its cohens kappa with any other validation or original annotation is equal to best pairwise cohens kappa,
- it completely matches original annotation,
- it completely matches any previous validation.

So to empty validations will match and the second one (same as first one) would be selected as canonical. But if there are some defined best cohens kappa then some previous validation could be selected cause it matches first condition. This exactly what happened to your example.

I understand that current result is not what you intended or expected, but rather than deleting validations I can propose 2 solutions:

1. Update resolving rules so that complete match will always be selected first.
2. Delete (or mark deleting) the whole series_tag, this is for case it don't make sense at all.

I vote for 1 since it's more explicit and easier to implement.

**Comment by idrdex** [comment] 2015-10-01 13:39
Let's start with 1 since easiest to implement and it will fix current problem. But eventually we should implement 2. I (and others) need the ability to clean up bad kappas before analysis. Moderators of sorts. Thx. 

dex*

**Comment by Suor** [comment] 2015-10-02 11:20
Implemented 1 and updated all canonical annotations.

On 2. I can add analysis parameter to only select annotations with cohens kappas more than it. Or fleiss kappa. And we should decide how to handle undefined kappa cases. This way we shouldn't need editing/deleting annotations themselves.

**Comment by idrdex** [comment] 2015-10-02 15:50
I don't think complicating analyses is the answer. Analyses should always use cannonical calls. A moderator needs the ability to curate the annotations easily. We need an ignore functionality, I agree not a good idea to delete anything. But for any series tag, I should be able to ignore specific users' annotations as needed. Ignore all annotations effectively deletes the series_tag.

**Comment by idrdex** [comment] 2015-10-02 15:54
I think it's worth the effort to implement. We want to be a source of the best annotations available period. And statistics to support them. So the annotations have to be invariant and paramaterized for quality by their kappas. We want out kappa distribution to converge on 1 with time.

**Comment by Suor** [comment] 2015-10-02 16:01
But canonical doesn't mean good or finished or confirmed at all, it's just best what we have at the moment for each series tag. Using all canonical = using source data of varying quality from good to completely random and unconfirmed . 

A few examples:
- if there is only annotation without any validations then it will be canonical, though it's unconfirmed and could be completely random.
- if there is single validation, which doesn't make sense at all (kappa ~ 0), then it will be selected as having best kappa.

When making canonical annotations we discussed that they will be filtered so that analysis will decide what quality of data it uses.

**Comment by Suor** [comment] 2015-10-02 16:11
The alternative to filtering annotations in analysis is filtering them statically, i.e. adding some `good` flag to them so that analysis will always select only good ones. This way bad (in-progress/unconfirmed) ones still could be examined on annotations page.

**Comment by idrdex** [comment] 2015-10-02 16:27
That functionality almost already exists via a modifier query. Ie gse_name != 'GSE...'  I agree not pretty, but can be used to filter for inclusion or exclusion explicitly.

**Comment by idrdex** [comment] 2015-10-02 17:01
Can't we keep undefined kappa as undefined explicitly? There is no good answer. Which is why I think cannonical calls must stay invariant and that is what analysis uses. I guess another control to filter samples for analysis  by kappa still makes sense. We should eventually implement that as well.

**Comment by idrdex** [comment] 2015-10-02 17:04
The nice thing is that 90% of initial annotations are good. The community's goal should be to transparently fix the remaining 10%. Curation by delete/ignore functionality explicitly addresses QC.

**Comment by Suor** [comment] 2015-10-02 17:08
I don't understand what you mean by "Can't we keep undefined kappa as undefined explicitly?" And kappa is kappa, if it's undefined then it is, I don't propose filling it with anything.

**Comment by idrdex** [comment] 2015-10-02 17:12
The only reason undefined kappa is an issue would be for a kappa filter on analysis.  If it is set, then all undefined kappas would have to be ignored.

**Comment by Suor** [comment] 2015-10-02 17:15
Yeah, filter either dynamic or static should be smart about that. E.g. accept all confirmed with exact matches and filter the rest by kappa.

On the other hand, undefined kappas happen when we have single class serie and that are excluded from analysis anyway, so maybe this is not an issue at all.

**Comment by idrdex** [comment] 2015-10-02 18:48
Yup. Agreed. https://github.com/idrdex/star-django/issues/28 Solves undefined kappa problem.

**Comment by Suor** [comment] 2015-10-09 06:18
Do we still need this deletion?

**Comment by idrdex** [comment] 2015-10-09 14:54
More an ignore functionality. If word annotations are not counted in kappa stats.

**Comment by idrdex** [comment] 2015-10-09 20:30
And only specialized moderators can ignore annotations.

**Comment by Suor** [comment] 2015-10-20 09:05
Added an ability to ignore serie validations. To do that click cross in corresponding header on [sample annotations page](http://dev.stargeo.io/annotations/2/samples/).

Do you also need to ignore original annotation or even hide the whole thing?

**Comment by Suor** [comment] 2015-10-20 09:08
Anyway reopen if yes.

**Closed by Suor** 2015-10-20 09:08 UTC
